GET http://localhost:8080/example_mvc_war/sum/2/2
Cache-Control: no-cache

###

GET http://localhost:8080/example_mvc_war/sub/7/12
Cache-Control: no-cache

###

GET http://localhost:8080/example_mvc_war/mul/4/3
Cache-Control: no-cache

###

GET http://localhost:8080/example_mvc_war/div/4/5
Cache-Control: no-cache

###

GET http://localhost:8080/example_mvc_war/div/4/0
Cache-Control: no-cache

###
