POST http://localhost:8080/example_mvc_war/convert
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "value": "500",
  "unit": "METERS",
  "to": "KILOMETERS"
}

###

POST http://localhost:8080/example_mvc_war/convert
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "value": "500",
  "unit": "METERS",
  "to": "GRAMS"
}

###

POST http://localhost:8080/example_mvc_war/convert
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{
  "unit": "WRONG"
}

###
